// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdS5zfKP1loyiWI1Tg_MdQmMlz7td8sLI',
    appId: '1:812747258347:web:9f9cbc540d328b997001ae',
    messagingSenderId: '812747258347',
    projectId: 'chmonitor-d6309',
    authDomain: 'chmonitor-d6309.firebaseapp.com',
    databaseURL: 'https://chmonitor-d6309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chmonitor-d6309.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA73da3PQBKokxlBU9hWEDfFeIsnSg9D0s',
    appId: '1:812747258347:android:b66ccc86e7120ca67001ae',
    messagingSenderId: '812747258347',
    projectId: 'chmonitor-d6309',
    databaseURL: 'https://chmonitor-d6309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chmonitor-d6309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQhXpDRcdjcM1zwKJ8cnCGyvfVaALoZ8k',
    appId: '1:812747258347:ios:c3b799c9bf4261f27001ae',
    messagingSenderId: '812747258347',
    projectId: 'chmonitor-d6309',
    databaseURL: 'https://chmonitor-d6309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chmonitor-d6309.appspot.com',
    iosClientId: '812747258347-pt9ke2vqpaq849tn4go0q65f57h14ssu.apps.googleusercontent.com',
    iosBundleId: 'com.example.prac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQhXpDRcdjcM1zwKJ8cnCGyvfVaALoZ8k',
    appId: '1:812747258347:ios:dc020721322f111e7001ae',
    messagingSenderId: '812747258347',
    projectId: 'chmonitor-d6309',
    databaseURL: 'https://chmonitor-d6309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chmonitor-d6309.appspot.com',
    iosClientId: '812747258347-n0bqlu6irkput3ce42ll06ban0nvb9un.apps.googleusercontent.com',
    iosBundleId: 'com.example.prac.RunnerTests',
  );
}
